from .auth import AuthService
from .email import EmailService
from .faculty import FacultyService
from .lecturer import LecturerService
from .speciality import SpecialityService
from .student import StudentService
from .user import UserService
from .lecturer_request import LecturerRequestService
from .session import SessionService
from .taught_course import TaughtCourseService
from .speciality_course import SpecialityCourseService
from .course_lecturer import CourseLecturerService
from .course_enrollment import CourseEnrollmentService
from .post import PostService
from .comment import CommentService
from .lecture import LectureService
from .file import FileService
from .question import QuestionService
from .quiz_result import QuizResultService
