"""Adding unique constraints to Students table

Revision ID: dec13b9ef5c8
Revises: d0cf2dff32b6
Create Date: 2023-12-04 17:37:21.951057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec13b9ef5c8'
down_revision: Union[str, None] = 'd0cf2dff32b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'faculties', ['name'])
    op.create_unique_constraint('email_faculty_constraint', 'students', ['email', 'faculty_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email_faculty_constraint', 'students', type_='unique')
    op.drop_constraint(None, 'faculties', type_='unique')
    # ### end Alembic commands ###
