"""Erasing birthdate column in user table

Revision ID: e641b69d5819
Revises: c92d852eeb14
Create Date: 2024-01-13 02:57:18.351050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e641b69d5819'
down_revision: Union[str, None] = 'c92d852eeb14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthdate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
