"""Replacing username column with first_name and last_name in user table

Revision ID: c6e6c5d54c1c
Revises: e641b69d5819
Create Date: 2024-01-13 03:16:39.596920

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6e6c5d54c1c"
down_revision: Union[str, None] = "e641b69d5819"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("first_name", sa.String(length=64), nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("last_name", sa.String(length=64), nullable=False),
    )
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "username", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
