"""Editing Students, Lecturers and Supervisors

Revision ID: 1aa74462f1c4
Revises: 6c4e81b14b46
Create Date: 2024-01-14 04:26:07.721967

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1aa74462f1c4"
down_revision: Union[str, None] = "6c4e81b14b46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("students_user_id_fkey", "students", type_="foreignkey")
    op.execute(
        """
    ALTER TABLE students
    ALTER COLUMN user_id TYPE UUID
    USING user_id::uuid
"""
    )
    op.alter_column(
        "students",
        "user_id",
        existing_type=sa.VARCHAR(length=640),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.create_foreign_key(
        "students_user_id_fkey",
        "students",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("students_user_id_fkey", "students", type_="foreignkey")
    op.create_foreign_key(
        "students_user_id_fkey",
        "students",
        "users",
        ["user_id"],
        ["email"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column(
        "students",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=640),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
