"""Deleting semesters, classes tables

Revision ID: f9cc451ff2aa
Revises: 69805b5ddbb0
Create Date: 2024-01-16 19:04:50.088293

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9cc451ff2aa"
down_revision: Union[str, None] = "69805b5ddbb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("faculties", sa.Column("max_class", sa.Integer(), nullable=True))
    op.drop_constraint("students_class_id_fkey", "students", type_="foreignkey")
    op.drop_constraint(
        "study_periods_current_class_fkey", "study_periods", type_="foreignkey"
    )
    op.drop_constraint(
        "study_periods_semester_fkey", "study_periods", type_="foreignkey"
    )
    op.drop_table("classes")
    op.drop_table("semesters")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "study_periods_semester_fkey",
        "study_periods",
        "semesters",
        ["semester"],
        ["name"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "study_periods_current_class_fkey",
        "study_periods",
        "classes",
        ["current_class"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "students_class_id_fkey",
        "students",
        "classes",
        ["class_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("faculties", "max_class")
    op.create_table(
        "classes",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="classes_pkey"),
        sa.UniqueConstraint("id", name="classes_id_key"),
    )
    op.create_table(
        "semesters",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("name", name="semesters_pkey"),
        sa.UniqueConstraint("name", name="semesters_name_key"),
    )
    # ### end Alembic commands ###
