"""adding birthdate

Revision ID: 1edeb4b3702e
Revises: eb2db0ed91d4
Create Date: 2023-11-16 22:18:09.956454

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1edeb4b3702e"
down_revision: Union[str, None] = "eb2db0ed91d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("birthdate", sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "birthdate")
    # ### end Alembic commands ###
