"""Update Student

Revision ID: 3cd266e428db
Revises: 7a30fa6e5b63
Create Date: 2023-11-17 15:02:25.009710

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cd266e428db"
down_revision: Union[str, None] = "7a30fa6e5b63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "faculty", ["name"])
    op.add_column(
        "student", sa.Column("student_email", sa.String(length=640), nullable=False)
    )
    op.create_unique_constraint(None, "student", ["student_id"])
    op.create_foreign_key(
        None,
        "student",
        "user",
        ["student_email"],
        ["email"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "student", type_="foreignkey")
    op.drop_constraint(None, "student", type_="unique")
    op.drop_column("student", "student_email")
    op.drop_constraint(None, "faculty", type_="unique")
    # ### end Alembic commands ###
