"""Create Faculty and Student

Revision ID: 7a30fa6e5b63
Revises: 1edeb4b3702e
Create Date: 2023-11-17 14:17:32.916419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a30fa6e5b63'
down_revision: Union[str, None] = '1edeb4b3702e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('name', sa.String(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('faculty_name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['faculty_name'], ['faculty.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('faculty')
    # ### end Alembic commands ###
