"""Add Unique  Student

Revision ID: 05261adca4c8
Revises: c89538bbbbf3
Create Date: 2023-11-18 00:27:43.880560

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05261adca4c8"
down_revision: Union[str, None] = "c89538bbbbf3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "student_constraint", "student", ["university_id", "faculty_name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("student_constraint", "student", type_="unique")
    # ### end Alembic commands ###
