"""Added Sepcialities table

Revision ID: d1453659e39a
Revises: 5a240fd8c924
Create Date: 2023-12-19 23:26:30.283689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1453659e39a'
down_revision: Union[str, None] = '5a240fd8c924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialities',
    sa.Column('name', sa.String(length=32), autoincrement=False, nullable=False),
    sa.Column('faculty_name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['faculty_name'], ['faculties.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_unique_constraint(None, 'courses', ['name'])
    op.drop_constraint('email_faculty_constraint', 'students', type_='unique')
    op.drop_constraint('student_faculty_constraint', 'students', type_='unique')
    op.drop_constraint('students_faculty_name_fkey', 'students', type_='foreignkey')
    op.drop_column('students', 'faculty_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('faculty_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.create_foreign_key('students_faculty_name_fkey', 'students', 'faculties', ['faculty_name'], ['name'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_unique_constraint('student_faculty_constraint', 'students', ['university_id', 'faculty_name'])
    op.create_unique_constraint('email_faculty_constraint', 'students', ['email', 'faculty_name'])
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_table('specialities')
    # ### end Alembic commands ###
