"""Added Sepcialities table and unique constraints

Revision ID: 245021a8c45b
Revises: b693c869e611
Create Date: 2023-12-19 23:53:58.117980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245021a8c45b'
down_revision: Union[str, None] = 'b693c869e611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('email_speciality_constraint', 'students', ['email', 'speciality_name'])
    op.create_unique_constraint('student_speciality_constraint', 'students', ['university_id', 'speciality_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_speciality_constraint', 'students', type_='unique')
    op.drop_constraint('email_speciality_constraint', 'students', type_='unique')
    # ### end Alembic commands ###
