"""Added Sepcialities table

Revision ID: b693c869e611
Revises: d1453659e39a
Create Date: 2023-12-19 23:48:49.596625

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b693c869e611"
down_revision: Union[str, None] = "d1453659e39a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "specialities", ["name"])
    op.add_column(
        "students", sa.Column("speciality_name", sa.String(length=32), nullable=True)
    )
    op.create_foreign_key(
        None,
        "students",
        "specialities",
        ["speciality_name"],
        ["name"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "students", type_="foreignkey")
    op.drop_column("students", "speciality_name")
    op.drop_constraint(None, "specialities", type_="unique")
    # ### end Alembic commands ###
