"""Delete study_periods relations

Revision ID: 20240308_21_21_42
Revises: 20240308_21_05_58
Create Date: 2024-03-08 21:21:42.206667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240308_21_21_42"
down_revision: Union[str, None] = "20240308_21_05_58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "taught_courses",
        "course_name",
        existing_type=sa.VARCHAR(length=32),
        nullable=False,
    )
    op.drop_constraint(
        "taught_courses_study_period_id_fkey", "taught_courses", type_="foreignkey"
    )
    op.drop_column("taught_courses", "study_period_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "taught_courses",
        sa.Column(
            "study_period_id", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "taught_courses_study_period_id_fkey",
        "taught_courses",
        "study_periods",
        ["study_period_id"],
        ["id"],
    )
    op.alter_column(
        "taught_courses",
        "course_name",
        existing_type=sa.VARCHAR(length=32),
        nullable=True,
    )
    # ### end Alembic commands ###
