"""Add marks column to quizzes table

Revision ID: 20240225_19_19_22
Revises: 20240225_18_48_38
Create Date: 2024-02-25 19:19:22.566585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240225_19_19_22"
down_revision: Union[str, None] = "20240225_18_48_38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("quizzes", sa.Column("mark", sa.Integer(), nullable=False))
    op.create_check_constraint(
        constraint_name="mark_is_postive", condition="mark > 0", table_name="quizzes"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quizzes", "mark")
    # ### end Alembic commands ###
