"""Remove index to name in faculties table

Revision ID: 20240403_03_06_56
Revises: 20240403_02_47_56
Create Date: 2024-04-03 03:06:56.065888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240403_03_06_56"
down_revision: Union[str, None] = "20240403_02_47_56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_faculties_name", table_name="faculties")
    op.create_unique_constraint("name_unique", "faculties", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("name_unique", "faculties", type_="unique")
    op.create_index("ix_faculties_name", "faculties", ["name"], unique=False)
    # ### end Alembic commands ###
