"""Add end_date and start_date for quizzes

Revision ID: 20240225_22_46_14
Revises: 20240225_20_20_49
Create Date: 2024-02-25 22:46:14.385885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240225_22_46_14"
down_revision: Union[str, None] = "20240225_20_20_49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quizzes",
        sa.Column(
            "start_date",
            sa.Integer(),
            server_default=sa.text("extract(epoch FROM now())"),
            nullable=False,
        ),
    )
    op.add_column(
        "quizzes",
        sa.Column(
            "end_date",
            sa.Integer(),
            server_default=sa.text("extract(epoch FROM now())"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quizzes", "end_date")
    op.drop_column("quizzes", "start_date")
    # ### end Alembic commands ###
