"""Make is_freshman not nullable in students table

Revision ID: 20240406_19_05_58
Revises: 20240406_19_03_49
Create Date: 2024-04-06 19:05:58.355297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240406_19_05_58"
down_revision: Union[str, None] = "20240406_19_03_49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "students", "is_freshman", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("students", "is_freshman", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
