"""Adding enrolled_courses table

Revision ID: 20240217_03_24_41
Revises: 20240216_21_46_21
Create Date: 2024-02-17 03:24:41.448878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240217_03_24_41"
down_revision: Union[str, None] = "20240216_21_46_21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enrolled_courses",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid7()"), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("specialization_course_id", sa.UUID(), nullable=False),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["specialization_course_id"],
            ["specialities_courses.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "student_id",
            "specialization_course_id",
            name="student_id_specialization_course_id_constraint",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("enrolled_courses")
    # ### end Alembic commands ###
