"""Edit courses

Revision ID: 20240308_21_05_58
Revises: 20240308_17_46_25
Create Date: 2024-03-08 21:05:58.386997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240308_21_05_58"
down_revision: Union[str, None] = "20240308_17_46_25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("name_speciality_id_constraint", "courses", type_="unique")
    op.drop_constraint("speciality_id_courses_fk", "courses", type_="foreignkey")
    op.drop_constraint(
        "taught_courses_course_id_fk", "taught_courses", type_="foreignkey"
    )
    op.drop_column("courses", "id")
    op.drop_column("courses", "speciality_id")
    op.drop_constraint(
        "name_study_period_id_constraint", "taught_courses", type_="unique"
    )
    op.drop_column("taught_courses", "name")
    op.drop_column("taught_courses", "course_id")
    op.create_primary_key(
        constraint_name="courses_pkey", table_name="courses", columns=["name"]
    )
    op.add_column(
        "taught_courses",
        sa.Column("course_name", sa.String(length=32), nullable=True, default="Base"),
    )
    op.alter_column(
        "taught_courses", "description", existing_type=sa.TEXT(), nullable=False
    )
    op.create_foreign_key(
        "course_name_fk",
        "taught_courses",
        "courses",
        ["course_name"],
        ["name"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "taught_courses",
        sa.Column("course_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "taught_courses",
        sa.Column("name", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    )
    op.drop_constraint("course_name_fk", "taught_courses", type_="foreignkey")
    op.create_foreign_key(
        "taught_courses_course_id_fk",
        "taught_courses",
        "courses",
        ["course_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        "name_study_period_id_constraint", "taught_courses", ["name", "study_period_id"]
    )
    op.alter_column(
        "taught_courses", "description", existing_type=sa.TEXT(), nullable=True
    )
    op.drop_column("taught_courses", "course_name")
    op.add_column(
        "courses",
        sa.Column("speciality_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "courses",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid7()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "speciality_id_courses_fk",
        "courses",
        "specialities",
        ["speciality_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        "name_speciality_id_constraint", "courses", ["name", "speciality_id"]
    )
    # ### end Alembic commands ###
