"""Add non_duplicated_file_lecture_constraint

Revision ID: 20240219_17_57_17
Revises: 20240219_17_51_22
Create Date: 2024-02-19 17:57:17.537586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240219_17_57_17"
down_revision: Union[str, None] = "20240219_17_51_22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "non_duplicated_file_lecture_constraint", "lectures", ["course_id", "file_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "non_duplicated_file_lecture_constraint", "lectures", type_="unique"
    )
    # ### end Alembic commands ###
