"""Edit academic_year in study_periods

Revision ID: 20240308_17_11_42
Revises: 20240228_01_40_07
Create Date: 2024-03-08 17:11:42.332496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240308_17_11_42"
down_revision: Union[str, None] = "20240228_01_40_07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE study_periods SET academic_year = 2024;")
    op.execute(
        "ALTER TABLE study_periods ALTER COLUMN academic_year TYPE INTEGER USING academic_year::integer;"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "study_periods",
        "academic_year",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
