"""Make speciality_course_id not null in taught_courses table

Revision ID: 20240309_01_07_32
Revises: 20240309_01_04_27
Create Date: 2024-03-09 01:07:32.758056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240309_01_07_32"
down_revision: Union[str, None] = "20240309_01_04_27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sqltext="""
        UPDATE taught_courses SET speciality_course_id = (
               SELECT id FROM specialities_courses LIMIT(1)
               ), year = 2025
                WHERE speciality_course_id IS NULL;
                """
    )
    op.alter_column(
        "taught_courses",
        "speciality_course_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "taught_courses", "speciality_course_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###
