"""Add quizzes table

Revision ID: 20240225_18_48_38
Revises: 20240225_02_42_12
Create Date: 2024-02-25 18:48:38.325652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240225_18_48_38"
down_revision: Union[str, None] = "20240225_02_42_12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quizzes",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid7()"), nullable=False),
        sa.Column("lecturer_course_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("number_of_questions", sa.Integer(), nullable=False),
        sa.Column(
            "added_at",
            sa.Integer(),
            server_default=sa.text("extract(epoch FROM now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.Integer(),
            server_default=sa.text("extract(epoch FROM now())"),
            nullable=False,
        ),
        sa.CheckConstraint("duration > 0", name="duration_is_positive"),
        sa.ForeignKeyConstraint(
            ["lecturer_course_id"],
            ["courses_lecturers.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "title", "lecturer_course_id", name="unique_quiz_in_course"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quizzes")
    # ### end Alembic commands ###
