"""Fixing courses primary key

Revision ID: 20240216_21_26_13
Revises: 20240216_21_09_35
Create Date: 2024-02-16 21:26:13.327092

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240216_21_26_13"
down_revision: Union[str, None] = "20240216_21_09_35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("courses_pkey", "courses", type_="primary")
    op.create_primary_key("courses_pkey", "courses", ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("courses_pkey", "courses", type_="primary")
    op.create_primary_key("courses_pkey", "courses", ["name"])
    # ### end Alembic commands ###
