"""delete positive constraint quizzes_resutls

Revision ID: 20240812_09_48_22
Revises: 20240811_02_39_17
Create Date: 2024-08-12 09:48:22.421614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240812_09_48_22"
down_revision: Union[str, None] = "20240811_02_39_17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("result_is_positive", "quizzes_results", type_="check")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint("result_is_positive", "quizzes_results", "result > 0")
    # ### end Alembic commands ###
