"""add is_approved column to lecturers table

Revision ID: 20240811_02_39_17
Revises: 20240731_00_53_03
Create Date: 2024-08-11 02:39:17.995354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240811_02_39_17"
down_revision: Union[str, None] = "20240731_00_53_03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lecturers", sa.Column("is_approved", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lecturers", "is_approved")
    # ### end Alembic commands ###
