"""Add device_name to active_sessions table

Revision ID: 20240402_17_32_12
Revises: 20240314_19_32_50
Create Date: 2024-04-02 17:32:12.812656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240402_17_32_12"
down_revision: Union[str, None] = "20240314_19_32_50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "active_sessions", sa.Column("device_name", sa.String(length=44), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("active_sessions", "device_name")
    # ### end Alembic commands ###
