"""Add speciality_course_id to taught_courses table

Revision ID: 20240309_01_04_27
Revises: 20240309_00_28_54
Create Date: 2024-03-09 01:04:27.775880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240309_01_04_27"
down_revision: Union[str, None] = "20240309_00_28_54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses_requests", sa.Column("taught_course_id", sa.UUID(), nullable=False)
    )
    op.drop_constraint(
        "specialization_course_id_fkey", "courses_requests", type_="foreignkey"
    )
    op.create_foreign_key(
        "taught_course_id_fkey",
        "courses_requests",
        "taught_courses",
        ["taught_course_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("courses_requests", "specialization_course_id")
    op.add_column(
        "taught_courses", sa.Column("speciality_course_id", sa.UUID(), nullable=True)
    )
    op.create_unique_constraint(
        "unique_coures_in_year_constraint",
        "taught_courses",
        ["speciality_course_id", "year"],
    )
    op.create_foreign_key(
        "speciality_course_id_fkey",
        "taught_courses",
        "specialities_courses",
        ["speciality_course_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "speciality_course_id_fkey", "taught_courses", type_="foreignkey"
    )
    op.drop_constraint(
        "unique_coures_in_year_constraint", "taught_courses", type_="unique"
    )
    op.drop_column("taught_courses", "speciality_course_id")
    op.add_column(
        "courses_requests",
        sa.Column(
            "specialization_course_id", sa.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint("taught_course_id_fkey", "courses_requests", type_="foreignkey")
    op.create_foreign_key(
        "specialization_course_id_fkey",
        "courses_requests",
        "specialities_courses",
        ["specialization_course_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("courses_requests", "taught_course_id")
    # ### end Alembic commands ###
