"""Repalce course_id, author_id with course_lecture_id

Revision ID: 20240225_19_27_18
Revises: 20240225_19_19_22
Create Date: 2024-02-25 19:27:18.805740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240225_19_27_18"
down_revision: Union[str, None] = "20240225_19_19_22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions",
        sa.Column("lecturer_course_id", sa.UUID(), nullable=True),
    )
    op.drop_constraint("unique_questions_in_course", "questions", type_="unique")
    op.create_unique_constraint(
        "unique_questions_in_course",
        "questions",
        ["lecturer_course_id", "body", "choices", "right_choice"],
    )
    op.drop_constraint("questions_course_id_fkey", "questions", type_="foreignkey")
    op.drop_constraint("questions_author_id_fkey", "questions", type_="foreignkey")
    op.create_foreign_key(
        None,
        "questions",
        "courses_lecturers",
        ["lecturer_course_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("questions", "course_id")
    op.drop_column("questions", "author_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions",
        sa.Column("author_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "questions",
        sa.Column("course_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("lecturer_course_id_fkey", "questions", type_="foreignkey")
    op.create_foreign_key(
        "questions_author_id_fkey",
        "questions",
        "users",
        ["author_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "questions_course_id_fkey",
        "questions",
        "taught_courses",
        ["course_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint("unique_questions_in_course", "questions", type_="unique")
    op.create_unique_constraint(
        "unique_questions_in_course",
        "questions",
        ["course_id", "body", "choices", "right_choice"],
    )
    op.drop_column("questions", "lecturer_course_id")
    # ### end Alembic commands ###
