"""Add index to name in faculties table

Revision ID: 20240403_02_41_15
Revises: 20240402_17_35_06
Create Date: 2024-04-03 02:41:15.064651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240403_02_41_15"
down_revision: Union[str, None] = "20240402_17_35_06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("faculties_name_key", "faculties", type_="unique")
    op.create_index(op.f("ix_faculties_name"), "faculties", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_faculties_name"), table_name="faculties")
    op.create_unique_constraint("faculties_name_key", "faculties", ["name"])
    # ### end Alembic commands ###
