"""Edit start_date and end_date in quizzes

Revision ID: 20240225_23_32_57
Revises: 20240225_22_46_14
Create Date: 2024-02-25 23:32:57.860365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240225_23_32_57"
down_revision: Union[str, None] = "20240225_22_46_14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quizzes",
        "start_date",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "quizzes",
        "end_date",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quizzes",
        "end_date",
        existing_type=sa.INTEGER(),
        server_default=sa.text("EXTRACT(epoch FROM now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "quizzes",
        "start_date",
        existing_type=sa.INTEGER(),
        server_default=sa.text("EXTRACT(epoch FROM now())"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
