"""Delete study_periods table

Revision ID: 20240308_22_15_15
Revises: 20240308_22_09_08
Create Date: 2024-03-08 22:15:15.756326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240308_22_15_15"
down_revision: Union[str, None] = "20240308_22_09_08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("study_periods")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "study_periods",
        sa.Column("id", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("academic_year", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("current_class", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("semester", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="study_periods_pkey"),
        sa.UniqueConstraint(
            "academic_year",
            "current_class",
            "semester",
            name="non_duplicated_constraint",
        ),
        sa.UniqueConstraint("id", name="study_periods_id_key"),
    )
    # ### end Alembic commands ###
