"""Add courses_requests table

Revision ID: 20240228_01_40_07
Revises: 20240228_00_24_12
Create Date: 2024-02-28 01:40:07.332887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240228_01_40_07"
down_revision: Union[str, None] = "20240228_00_24_12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses_requests",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("specialization_course_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=50), nullable=True),
        sa.Column("is_accepted", sa.Boolean(), nullable=True),
        sa.Column("processed_at", sa.Integer(), nullable=True),
        sa.Column("processed_by", sa.UUID(), nullable=True),
        sa.Column(
            "added_at",
            sa.Integer(),
            server_default=sa.text("extract(epoch FROM now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.Integer(),
            server_default=sa.text("extract(epoch FROM now())"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid7()"), nullable=False),
        sa.CheckConstraint("processed_at > 0", name="ensure_is_accepted_positive"),
        sa.CheckConstraint(
            "processed_by <> student_id", name="user_didn't_accept_itself"
        ),
        sa.ForeignKeyConstraint(
            ["processed_by"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["specialization_course_id"],
            ["specialities_courses.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
            name="specialization_course_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
            name="student_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("courses_requests")
    # ### end Alembic commands ###
