"""Add check constraint for  current_class and semester in specialities_courses

Revision ID: 20240308_21_43_52
Revises: 20240308_21_39_44
Create Date: 2024-03-08 21:43:52.674646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240308_21_43_52"
down_revision: Union[str, None] = "20240308_21_39_44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        table_name="specialities_courses",
        constraint_name="chech_current_class",
        condition="semester in (1, 2)",
    )
    op.create_check_constraint(
        table_name="specialities_courses",
        constraint_name="check_semester",
        condition="current_class <= 6 and current_class >=1",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        table_name="specialities_courses",
        constraint_name="chech_current_class",
    )
    op.drop_constraint(
        table_name="specialities_courses",
        constraint_name="check_semester",
    )
    # ### end Alembic commands ###
