"""Change relation from courses to taught_courses in courses_lecturers

Revision ID: 20240225_19_52_24
Revises: 20240225_19_27_18
Create Date: 2024-02-25 19:52:24.908518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240225_19_52_24"
down_revision: Union[str, None] = "20240225_19_27_18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "courses_lecturers_course_id_fkey", "courses_lecturers", type_="foreignkey"
    )
    op.create_foreign_key(
        "taught_course_id_fkey",
        "courses_lecturers",
        "taught_courses",
        ["course_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("taught_course_id_fkey", "courses_lecturers", type_="foreignkey")
    op.create_foreign_key(
        "courses_lecturers_course_id_fkey",
        "courses_lecturers",
        "courses",
        ["course_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
