"""Add active_sessions table

Revision ID: 20240313_00_27_33
Revises: 20240309_01_07_32
Create Date: 2024-03-13 00:27:33.486702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240313_00_27_33"
down_revision: Union[str, None] = "20240309_01_07_32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "active_sessions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token", sa.String(length=256), nullable=False),
        sa.Column("device_id", sa.String(length=44), nullable=False),
        sa.Column(
            "added_at",
            sa.Integer(),
            server_default=sa.text("extract(epoch FROM now())"),
            nullable=False,
        ),
        sa.Column("expire_at", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid7()"), nullable=False),
        sa.CheckConstraint("added_at > 0"),
        sa.CheckConstraint("expire_at > 0"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="user_id_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("refresh_token"),
        sa.UniqueConstraint("user_id", "device_id", name="unique_device_per_session"),
    )
    op.create_index(
        op.f("ix_active_sessions_user_id"), "active_sessions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_active_sessions_user_id"), table_name="active_sessions")
    op.drop_table("active_sessions")
    # ### end Alembic commands ###
