"""Add is_freshman column to students table

Revision ID: 20240406_19_03_49
Revises: 20240403_03_06_56
Create Date: 2024-04-06 19:03:49.508984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240406_19_03_49"
down_revision: Union[str, None] = "20240403_03_06_56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("is_freshman", sa.Boolean(), nullable=True))
    op.execute("UPDATE students SET is_freshman = true where is_freshman IS NULL;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "is_freshman")
    # ### end Alembic commands ###
