"""Make current_class and semester not null in specialities_courses

Revision ID: 20240308_21_39_44
Revises: 20240308_21_36_46
Create Date: 2024-03-08 21:39:44.872964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240308_21_39_44"
down_revision: Union[str, None] = "20240308_21_36_46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "specialities_courses",
        "current_class",
        existing_type=sa.SMALLINT(),
        nullable=False,
    )
    op.alter_column(
        "specialities_courses", "semester", existing_type=sa.SMALLINT(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "specialities_courses", "semester", existing_type=sa.SMALLINT(), nullable=True
    )
    op.alter_column(
        "specialities_courses",
        "current_class",
        existing_type=sa.SMALLINT(),
        nullable=True,
    )
    # ### end Alembic commands ###
