"""Repalce course_id, author_id with course_lecture_id in posts

Revision ID: 20240225_20_10_11
Revises: 20240225_19_59_56
Create Date: 2024-02-25 20:10:11.689980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240225_20_10_11"
down_revision: Union[str, None] = "20240225_19_59_56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("lecturer_course_id", sa.UUID(), nullable=True))
    op.drop_constraint("posts_course_id_fkey", "posts", type_="foreignkey")
    op.drop_constraint("posts_author_id_fkey", "posts", type_="foreignkey")
    op.create_foreign_key(
        "lecturer_course_id_fkey",
        "posts",
        "courses_lecturers",
        ["lecturer_course_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("posts", "course_id")
    op.drop_column("posts", "author_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("author_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "posts", sa.Column("course_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint("lecturer_course_id_fkey", "posts", type_="foreignkey")
    op.create_foreign_key(
        "posts_author_id_fkey",
        "posts",
        "users",
        ["author_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "posts_course_id_fkey",
        "posts",
        "taught_courses",
        ["course_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("posts", "lecturer_course_id")
    # ### end Alembic commands ###
