"""Reduce length of file_id from 30 to 10 in Files table

Revision ID: 20240619_22_39_26
Revises: 20240619_22_17_33
Create Date: 2024-06-19 22:39:26.598361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240619_22_39_26"
down_revision: Union[str, None] = "20240619_22_17_33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("name_files_unique", "files", type_="unique")
    op.create_unique_constraint("file_id_files_unique", "files", ["file_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("file_id_files_unique", "files", type_="unique")
    op.create_unique_constraint("name_files_unique", "files", ["name"])
    # ### end Alembic commands ###
