"""Fixing courses unique constraint id

Revision ID: 20240216_21_28_24
Revises: 20240216_21_26_13
Create Date: 2024-02-16 21:28:24.778341

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240216_21_28_24"
down_revision: Union[str, None] = "20240216_21_26_13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "taught_courses_course_id_fk", "taught_courses", type_="foreignkey"
    )
    op.drop_constraint("course_id_unique", "courses", type_="unique")
    op.create_foreign_key(
        constraint_name="taught_courses_course_id_fk",
        source_table="taught_courses",
        referent_table="courses",
        local_cols=["course_id"],
        remote_cols=["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("course_id_unique", "courses", ["id"])
    # ### end Alembic commands ###
