"""Edit relations in enrolled_courses

Revision ID: 20240309_00_28_54
Revises: 20240308_22_17_45
Create Date: 2024-03-09 00:28:54.861356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240309_00_28_54"
down_revision: Union[str, None] = "20240308_22_17_45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "enrolled_courses", sa.Column("taught_course_id", sa.UUID(), nullable=False)
    )
    op.drop_constraint(
        "student_id_specialization_course_id_constraint",
        "enrolled_courses",
        type_="unique",
    )
    op.create_unique_constraint(
        "student_course_unique_constraint",
        "enrolled_courses",
        ["student_id", "taught_course_id"],
    )
    op.drop_constraint(
        "enrolled_courses_specialization_course_id_fkey",
        "enrolled_courses",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "taught_course_id_fkey",
        "enrolled_courses",
        "taught_courses",
        ["taught_course_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("enrolled_courses", "specialization_course_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "enrolled_courses",
        sa.Column(
            "specialization_course_id", sa.UUID(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint("taught_course_id_fkey", "enrolled_courses", type_="foreignkey")
    op.create_foreign_key(
        "enrolled_courses_specialization_course_id_fkey",
        "enrolled_courses",
        "specialities_courses",
        ["specialization_course_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "student_course_unique_constraint", "enrolled_courses", type_="unique"
    )
    op.create_unique_constraint(
        "student_id_specialization_course_id_constraint",
        "enrolled_courses",
        ["student_id", "specialization_course_id"],
    )
    op.drop_column("enrolled_courses", "taught_course_id")
    # ### end Alembic commands ###
