"""Edit columns in study_periods

Revision ID: 20240308_17_46_25
Revises: 20240308_17_11_42
Create Date: 2024-03-08 17:46:25.918743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240308_17_46_25"
down_revision: Union[str, None] = "20240308_17_11_42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "taught_courses_study_period_id_fkey", "taught_courses", type_="foreignkey"
    )
    op.alter_column(
        "study_periods",
        "id",
        existing_type=sa.INTEGER(),
        server_default=None,
        type_=sa.String(length=10),
        existing_nullable=False,
    )
    op.alter_column(
        "study_periods",
        "academic_year",
        existing_type=sa.INTEGER(),
        type_=sa.SmallInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "study_periods",
        "current_class",
        existing_type=sa.INTEGER(),
        type_=sa.SmallInteger(),
        existing_nullable=False,
    )
    op.execute(
        "ALTER TABLE study_periods ALTER COLUMN semester TYPE SMALLINT USING semester::smallint;"
    )
    op.alter_column(
        "taught_courses",
        "study_period_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=10),
        existing_nullable=False,
    )
    op.create_foreign_key(
        "taught_courses_study_period_id_fkey",
        "taught_courses",
        "study_periods",
        ["study_period_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "taught_courses_study_period_id_fkey", "taught_courses", type_="foreignkey"
    )

    op.execute(
        "ALTER TABLE study_periods ALTER COLUMN id TYPE INTEGER USING id::integer;"
    )
    op.execute(
        "ALTER TABLE taught_courses ALTER COLUMN study_period_id TYPE INTEGER USING study_period_id::integer;"
    )
    op.execute(
        "ALTER TABLE taught_courses ALTER COLUMN study_period_id TYPE INTEGER USING study_period_id::integer;"
    )
    op.create_foreign_key(
        "taught_courses_study_period_id_fkey",
        "taught_courses",
        "study_periods",
        ["study_period_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column(
        "study_periods",
        "semester",
        existing_type=sa.SmallInteger(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "study_periods",
        "current_class",
        existing_type=sa.SmallInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "study_periods",
        "academic_year",
        existing_type=sa.SmallInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
