"""Add Semesters, Classes and Years tables

Revision ID: dd0a36b924e9
Revises: 76060c8157b9
Create Date: 2023-12-21 19:37:15.837593

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd0a36b924e9"
down_revision: Union[str, None] = "76060c8157b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # Adding classes from 1 to 6
    for value in range(1, 7):
        op.execute(f"INSERT INTO classes (id) VALUES ({value});")

    op.create_table(
        "semesters",
        sa.Column("name", sa.String(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("name"),
        sa.UniqueConstraint("name"),
    )

    # Adding First and Seconds Semesters
    op.execute("INSERT INTO semesters (name) VALUES ('First'), ('Second');")

    op.create_table(
        "years",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("academic_year", sa.String(), nullable=False),
        sa.Column("current_class", sa.Integer(), nullable=False),
        sa.Column("semester", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["current_class"], ["classes.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["semester"], ["semesters.name"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "academic_year",
            "current_class",
            "semester",
            name="non_duplicated_constraint",
        ),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("years")
    op.drop_table("semesters")
    op.drop_table("classes")
    # ### end Alembic commands ###
