"""Adding Lecturers table

Revision ID: 76060c8157b9
Revises: 245021a8c45b
Create Date: 2023-12-21 02:58:58.383286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76060c8157b9'
down_revision: Union[str, None] = '245021a8c45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecturers',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid7()'), nullable=False),
    sa.Column('email', sa.String(length=640), nullable=False),
    sa.Column('faculty_name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['users.email'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_name'], ['faculties.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'faculty_name', name='email_faculty_constraint')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecturers')
    # ### end Alembic commands ###
