"""Add TaughtCourses table

Revision ID: c92d852eeb14
Revises: dd0a36b924e9
Create Date: 2023-12-22 02:38:30.134769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92d852eeb14'
down_revision: Union[str, None] = 'dd0a36b924e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taught_courses',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid7()'), nullable=False),
    sa.Column('course_name', sa.String(length=32), nullable=False),
    sa.Column('speciality_name', sa.String(length=32), nullable=False),
    sa.Column('lecturer_id', sa.UUID(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_name'], ['courses.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speciality_name'], ['specialities.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['year_id'], ['years.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'classes', ['id'])
    op.create_unique_constraint(None, 'semesters', ['name'])
    op.create_unique_constraint(None, 'years', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'years', type_='unique')
    op.drop_constraint(None, 'semesters', type_='unique')
    op.drop_constraint(None, 'classes', type_='unique')
    op.drop_table('taught_courses')
    # ### end Alembic commands ###
