"""Editing courses table

Revision ID: 6b27697f3604
Revises: 1e3768839bd1
Create Date: 2024-01-31 18:39:59.427294

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b27697f3604"
down_revision: Union[str, None] = "1e3768839bd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE courses;")
    op.add_column(
        "courses",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid7()"), nullable=False),
    )
    op.add_column("courses", sa.Column("speciality_id", sa.UUID(), nullable=False))
    op.create_foreign_key(
        "course_speciality_fk",
        "courses",
        "specialities",
        ["speciality_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.execute("ALTER TABLE specialities DROP CONSTRAINT specialities_id_key CASCADE;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("specialities_id_key", "specialities", ["id"])
    op.drop_constraint("course_speciality_fk", "courses", type_="foreignkey")
    op.drop_column("courses", "speciality_id")
    op.drop_column("courses", "id")
    # ### end Alembic commands ###
