"""Adding unique constraints to courses

Revision ID: 55351f74c26d
Revises: 6b27697f3604
Create Date: 2024-01-31 19:13:45.804927

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55351f74c26d"
down_revision: Union[str, None] = "6b27697f3604"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE specialities ADD CONSTRAINT specialities_id_unique UNIQUE (id);"
    )
    op.create_foreign_key(
        "speciality_id_courses_fk",
        "courses",
        "specialities",
        ["speciality_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "speciality_id_students_fk",
        "students",
        "specialities",
        ["speciality_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        "name_speciality_id_constraint",
        "courses",
        ["name", "speciality_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("speciality_id_students_fk", "students", type_="foreignkey")
    op.drop_constraint("speciality_id_courses_fk", "courses", type_="foreignkey")
    op.drop_constraint("name_speciality_id_constraint", "courses", type_="unique")
    # ### end Alembic commands ###
