"""Adding taught_courses

Revision ID: f8521e18de73
Revises: 55351f74c26d
Create Date: 2024-01-31 21:24:52.817020

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8521e18de73"
down_revision: Union[str, None] = "55351f74c26d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taught_courses",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid7()"), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("study_period_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["study_period_id"],
            ["study_periods.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name", "study_period_id", name="name_study_period_id_constraint"
        ),
    )
    op.drop_constraint("courses_name_key", "courses", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("courses_name_key", "courses", ["name"])
    op.drop_table("taught_courses")
    # ### end Alembic commands ###
