"""Adding courses_lecturers table

Revision ID: d3de68fb8199
Revises: 79d28a3eeebf
Create Date: 2024-01-31 22:12:00.770128

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3de68fb8199"
down_revision: Union[str, None] = "79d28a3eeebf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses_lecturers",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid7()"), nullable=False),
        sa.Column("taught_course_id", sa.UUID(), nullable=False),
        sa.Column("lecturer_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lecturer_id"], ["lecturers.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["taught_course_id"],
            ["taught_courses.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "taught_course_id",
            "lecturer_id",
            name="taught_course_id_lecturer_id_constraint",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("courses_lecturers")
    # ### end Alembic commands ###
