"""Add uuid to Student

Revision ID: 9a27bf47d23d
Revises: a599137734d3
Create Date: 2023-11-17 23:45:48.927757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a27bf47d23d'
down_revision: Union[str, None] = 'a599137734d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('id', sa.UUID(), server_default=sa.text('uuid7()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'id')
    # ### end Alembic commands ###
