"""Update Student attributes name

Revision ID: a599137734d3
Revises: 3cd266e428db
Create Date: 2023-11-17 23:31:26.452101

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a599137734d3"
down_revision: Union[str, None] = "3cd266e428db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "student",
        sa.Column("university_id", sa.Integer(), autoincrement=False, nullable=False),
    )
    op.add_column("student", sa.Column("email", sa.String(length=640), nullable=False))
    op.drop_constraint("student_student_id_key", "student", type_="unique")
    op.create_unique_constraint(None, "student", ["university_id"])
    op.drop_constraint("student_student_email_fkey", "student", type_="foreignkey")
    op.create_foreign_key(
        None,
        "student",
        "user",
        ["email"],
        ["email"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("student", "student_id")
    op.drop_column("student", "student_email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "student",
        sa.Column(
            "student_email", sa.VARCHAR(length=640), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "student",
        sa.Column("student_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "student", type_="foreignkey")
    op.create_foreign_key(
        "student_student_email_fkey",
        "student",
        "user",
        ["student_email"],
        ["email"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "student", type_="unique")
    op.create_unique_constraint("student_student_id_key", "student", ["student_id"])
    op.drop_column("student", "email")
    op.drop_column("student", "university_id")
    # ### end Alembic commands ###
