"""Update Student univeristy_id and id

Revision ID: c89538bbbbf3
Revises: 9a27bf47d23d
Create Date: 2023-11-17 23:46:44.301583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89538bbbbf3'
down_revision: Union[str, None] = '9a27bf47d23d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_university_id_key', 'student', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('student_university_id_key', 'student', ['university_id'])
    # ### end Alembic commands ###
