"""Deleting semesters, classes tables

Revision ID: 42ca0aa2d900
Revises: f9cc451ff2aa
Create Date: 2024-01-16 19:07:53.093477

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42ca0aa2d900"
down_revision: Union[str, None] = "f9cc451ff2aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "faculties", "max_class", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("faculties", "max_class", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
