from .base import BaseModelView
from .course import CourseAdmin
from .course_lecturer import CourseLecturerAdmin
from .faculty import FacultyAdmin
from .lecturer import LecturerAdmin
from .lecturer import LecturerAdmin
from .speciality import SpecialityAdmin
from .student import StudentAdmin
from .taught_course import TaughtCourseAdmin
from .user import UserAdmin
from .speciality_course import SpecialityCourseAdmin
from .enrolled_course import EnrolledCourseAdmin
from .post import PostAdmin
from .comment import CommentAdmin
from .file import FileAdmin
from .lecture import LectureAdmin
from .question import QuestionAdmin
from .quiz import QuizAdmin
from .quiz_result import QuizResultAdmin
from .lecturer_request import LecturerRequestAdmin
from .course_request import CourseRequestAdmin
from .active_session import ActiveSessionAdmin
