from .auth import AdminAuth
from .views import (
    UserAdmin,
    FacultyAdmin,
    StudentAdmin,
    SpecialityAdmin,
    LecturerAdmin,
    CourseAdmin,
    TaughtCourseAdmin,
    CourseLecturerAdmin,
    SpecialityCourseAdmin,
    EnrolledCourseAdmin,
    PostAdmin,
    CommentAdmin,
    FileAdmin,
    LectureAdmin,
    QuestionAdmin,
    QuizAdmin,
    QuizResultAdmin,
    LecturerRequestAdmin,
    CourseRequestAdmin,
    ActiveSessionAdmin,
)
